project_id = "knivoexfpvqohsvpsziq"

[functions.auth-service]
verify_jwt = false

[functions.projects-service]
verify_jwt = false

[functions.access-service]
verify_jwt = false

[functions.capacity-service]
verify_jwt = false

[functions.retro-service]
verify_jwt = false