project_id = "knivoexfpvqohsvpsziq"

[functions.auth-service]
verify_jwt = false

[functions.projects-service]
verify_jwt = false

[functions.access-service]
verify_jwt = false

[functions.capacity-service]
verify_jwt = false

[functions.retro-service]
verify_jwt = false

[functions.roadmap-service]
verify_jwt = false

[functions.backlog-service]
verify_jwt = false

[functions.stakeholder-service]
verify_jwt = false

[functions.audit-service]
verify_jwt = false

[functions.workspace-service]
verify_jwt = false

[functions.wizard-service]
verify_jwt = false

[functions.department-service]
verify_jwt = false